### PR TITLE
Cmake gitlabci

### PR DESCRIPTION
**Pull request by nickma82**
Although I didn't test the packages itself, it now outputs rpm packages. You can easily download the build done on Fedora at the right hand side of the [gitlab-ci page](https://gitlab.com/nickma/mbusd/pipelines).
It's doing three build atm as you can see.

Questionable is why the mbusd bin's from inside the rpm and from the "raw build" aren't the same
E.g. [artifact 44090939](https://gitlab.com/nickma/mbusd/-/jobs/44090939/artifacts/download):
md5sum mbusd*
82208e13bb5a8cd0107caa8307d5bde5  mbusd
dbfa33ca4423f9eb31892a2358ce9540  mbusd_rpm

Maybe you could test the integrity?
Apart from that you are now able to *build a rpm package by yourself* by issuing a `make package` in the output.dir.

### CODE REVIEW

**Comment by 3cky** [comment]
> Questionable is why the mbusd bin's from inside the rpm and from the "raw build" aren't the same

Probably it's because the RPM binary is stripped and raw isn't?

> Maybe you could test the integrity?

I've successfully installed provided RPM in my Fedora 26 with no complaints from the OS, so it seems to be OK. :)

**Comment by nickma82** [comment]
> Probably it's because the RPM binary is stripped and raw isn't?

You where right and obviously they do differ in size - a lot 88K vs 40k.
Best

mbusd:     ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=36526683bbd4af2fcc34750016a4ab1877abb34a, not stripped

mbusd_rpm: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=36526683bbd4af2fcc34750016a4ab1877abb34a, strippe

ls -la mbusd* 
-rwxr-xr-x 1 nickma nickma 88K Dec 11 22:28 mbusd
-rwxr-xr-x 1 nickma nickma 40K Dec 11 22:28 mbusd_rpm

**Comment by nickma82** [comment]
Auto packaging is still looking good: https://gitlab.com/nickma/mbusd/pipelines/14988549

I did a lookup for travis-ci and I'd have to change the whole behavior in order to build rpm packages.

**Comment by 3cky** [comment]
Sorry for late response, I don't have much time for mbusd these weeks. Thank you for your contribution! I'm still thinking about the best way to provide mbusd as deb/rpm package. Probably, we should use Launchpad PPA/Fedora Copr infrastructure.

**Comment by nickma82** [comment]
> Sorry for late response, I don't have much time for mbusd these weeks.
No problem, I don't have time on a daily basis either. :)

> Probably, we should use Launchpad PPA/Fedora Copr infrastructure.
I know little about launchpad, does it support releasing of both rpm and deb packages?

Luckily this is not mutual exclusive. With this PR, one could (as I did) push a copy to gitlab.com and immediately a CI job is getting started building those three packages.
If you like, I could reduce the number of commits (best case to one)?

**Comment by nickma82** [comment]
Hi, just built a new snapshot of master:
https://gitlab.com/nickma/mbusd/pipelines/18399789/builds

Best

**Comment by 3cky** [comment]
@nickma82 merged, thank you for your contribution!

**Pull request merged**
