### PR TITLE
Gracefully handle incorrect Modbus/TCP length header

### PR DESCRIPTION
**Pull request by sgel83**
https://github.com/3cky/mbusd/issues/31

### CODE REVIEW

**Comment by 3cky** [comment]
@sgel83 thanks for your efforts. Unfortunately, handling of incorrect Modbus/TCP length header is a bit more complicated rather it seems. The main problem is when we read data from TCP connection it is not guaranteed we will get whole Modbus frame at once, so checking for the obtained data length is not sufficient because we don't know is there more data to read from the TCP socket or isn't, and that's why we need (correct) length field value in header. We also can deduce full Modbus/TCP frame length from its function code (and probably from following request parameters), but it requires far more changes in connection state handling code.

**Comment by sgel83** [comment]
@3cky 

So, what are the scenarios that cause this fragmentation?  Is it fragmentation due to TCP/MSS?  Or is it something that you have just seen with Modbus where it will fragment the payload as it pleases?

While this scenario is certainly more difficult, if I changed the code:

from

if (curconn->buf[MB_LENGTH_L] != (curconn->ctr - HDRSIZE))

to:

if (curconn->buf[MB_LENGTH_L] < (curconn->ctr - HDRSIZE))

I think this would suffice for my problem and not cause any issues with larger fragmented Modbus requests. Meaning it would only trigger when clearly the length header is wrong as even the current data we have is larger then what is defined.

What are your thoughts?

**Comment by 3cky** [comment]
@sgel83 

Well, let's imagine `read()` function returns only one byte each time called. That's perfectly possible, because read(2) man page [says](http://man7.org/linux/man-pages/man2/read.2.html):

> On success, the number of bytes read is returned (zero indicates end of file) [...]  It is not an error if this number is smaller than the number of bytes requested.

So, at some moment, we will get into state when`curconn->buf[MB_LENGTH_L] == (curconn->ctr - HDRSIZE)`, and if header length field will be incorrect, we'll miss it. While this situation is improbable, it's still possible.

Nevertheless, I'm currently working on more robust solution, so stay tuned. :)

**Comment by sgel83** [comment]
@3cky Thanks.  I tested your new code and it works perfectly.

**Pull request closed without merging**
