### PR TITLE
Systemd support

### PR DESCRIPTION
**Pull request by luuloe**
Hi 3cky,

For my home automation I needed a TCP to RS484 ModBus gateway. I found your mbusd project, remembered I had a spare Raspberry PI and thought it would be a cool project and a cheap solution. I started to experiment with mbusd and it is working great. However I have to start it by hand as it has no support for systemd, which is the standard on modern linux distributions like debian. Therefore I decided to add it with this pull request as the result.

This pull request incoorperates the following changes:
- systemd detection in AutoMake. If systemd is available then `sudo make install` installs the service file on the system
- systemd service runs in non-daemon mode -d as it is the standard for modern services to let systemd do the forking
- Added ability to gracefully terminate mbusd via SIGINT and SIGTERM signals
- Non-daemon mode logs to stderr so that lines are logged directly to the journal. stdout is buffered and as a results when using stdout log lines will become visible when terminating the service
- README.md is extended with systemd information

I hope you like it. Feel free to comment.

### CODE REVIEW

**Comment by 3cky** [comment]
Hello @luuloe! Thanks for your contribution since automatic mbusd startup is long standing feature request from users (#11 for example). This PR looks good to me, I will do some checks and then will merge it.

**Comment by luuloe** [comment]
Off course. Please check esspecially the AutoMake part thoroughly as I am not very familiar with it.

**Comment by nickma82** [comment]
Hi @3cky,
does your integration allow to run multiple mbusd's (with different arguments of course)?

Example use case: two different ModbusRTU lines.
Best

**Comment by nickma82** [comment]
@luuloe thanks for clarification! :)

**Pull request merged**
